#
# Autogenerated by Thrift Compiler (0.8.0)
#
# DO NOT EDIT UNLESS YOU ARE SURE THAT YOU KNOW WHAT YOU ARE DOING
#
#  options string: py
#

from thrift.Thrift import TType, TMessageType, TException
from ttypes import *

STATIC_INSTANCE = "00000000-0000-0000-0000-000000000000"
ERROR_APPLET = "@error"
DONE_APPLET = "@done"
