/**
 * Autogenerated by Thrift
 *
 * DO NOT EDIT UNLESS YOU ARE SURE THAT YOU KNOW WHAT YOU ARE DOING
 */
package org.remus.thrift;

import java.util.List;
import java.util.ArrayList;
import java.util.Map;
import java.util.HashMap;
import java.util.EnumMap;
import java.util.Set;
import java.util.HashSet;
import java.util.EnumSet;
import java.util.Collections;
import java.util.BitSet;
import java.nio.ByteBuffer;
import java.util.Arrays;
import org.slf4j.Logger;
import org.slf4j.LoggerFactory;

public class AppletRef implements org.apache.thrift.TBase<AppletRef, AppletRef._Fields>, java.io.Serializable, Cloneable {
  private static final org.apache.thrift.protocol.TStruct STRUCT_DESC = new org.apache.thrift.protocol.TStruct("AppletRef");

  private static final org.apache.thrift.protocol.TField PIPELINE_FIELD_DESC = new org.apache.thrift.protocol.TField("pipeline", org.apache.thrift.protocol.TType.STRING, (short)1);
  private static final org.apache.thrift.protocol.TField INSTANCE_FIELD_DESC = new org.apache.thrift.protocol.TField("instance", org.apache.thrift.protocol.TType.STRING, (short)2);
  private static final org.apache.thrift.protocol.TField APPLET_FIELD_DESC = new org.apache.thrift.protocol.TField("applet", org.apache.thrift.protocol.TType.STRING, (short)3);
  private static final org.apache.thrift.protocol.TField KEYS_FIELD_DESC = new org.apache.thrift.protocol.TField("keys", org.apache.thrift.protocol.TType.LIST, (short)4);

  public String pipeline;
  public String instance;
  public String applet;
  public List<String> keys;

  /** The set of fields this struct contains, along with convenience methods for finding and manipulating them. */
  public enum _Fields implements org.apache.thrift.TFieldIdEnum {
    PIPELINE((short)1, "pipeline"),
    INSTANCE((short)2, "instance"),
    APPLET((short)3, "applet"),
    KEYS((short)4, "keys");

    private static final Map<String, _Fields> byName = new HashMap<String, _Fields>();

    static {
      for (_Fields field : EnumSet.allOf(_Fields.class)) {
        byName.put(field.getFieldName(), field);
      }
    }

    /**
     * Find the _Fields constant that matches fieldId, or null if its not found.
     */
    public static _Fields findByThriftId(int fieldId) {
      switch(fieldId) {
        case 1: // PIPELINE
          return PIPELINE;
        case 2: // INSTANCE
          return INSTANCE;
        case 3: // APPLET
          return APPLET;
        case 4: // KEYS
          return KEYS;
        default:
          return null;
      }
    }

    /**
     * Find the _Fields constant that matches fieldId, throwing an exception
     * if it is not found.
     */
    public static _Fields findByThriftIdOrThrow(int fieldId) {
      _Fields fields = findByThriftId(fieldId);
      if (fields == null) throw new IllegalArgumentException("Field " + fieldId + " doesn't exist!");
      return fields;
    }

    /**
     * Find the _Fields constant that matches name, or null if its not found.
     */
    public static _Fields findByName(String name) {
      return byName.get(name);
    }

    private final short _thriftId;
    private final String _fieldName;

    _Fields(short thriftId, String fieldName) {
      _thriftId = thriftId;
      _fieldName = fieldName;
    }

    public short getThriftFieldId() {
      return _thriftId;
    }

    public String getFieldName() {
      return _fieldName;
    }
  }

  // isset id assignments

  public static final Map<_Fields, org.apache.thrift.meta_data.FieldMetaData> metaDataMap;
  static {
    Map<_Fields, org.apache.thrift.meta_data.FieldMetaData> tmpMap = new EnumMap<_Fields, org.apache.thrift.meta_data.FieldMetaData>(_Fields.class);
    tmpMap.put(_Fields.PIPELINE, new org.apache.thrift.meta_data.FieldMetaData("pipeline", org.apache.thrift.TFieldRequirementType.REQUIRED, 
        new org.apache.thrift.meta_data.FieldValueMetaData(org.apache.thrift.protocol.TType.STRING)));
    tmpMap.put(_Fields.INSTANCE, new org.apache.thrift.meta_data.FieldMetaData("instance", org.apache.thrift.TFieldRequirementType.REQUIRED, 
        new org.apache.thrift.meta_data.FieldValueMetaData(org.apache.thrift.protocol.TType.STRING)));
    tmpMap.put(_Fields.APPLET, new org.apache.thrift.meta_data.FieldMetaData("applet", org.apache.thrift.TFieldRequirementType.REQUIRED, 
        new org.apache.thrift.meta_data.FieldValueMetaData(org.apache.thrift.protocol.TType.STRING)));
    tmpMap.put(_Fields.KEYS, new org.apache.thrift.meta_data.FieldMetaData("keys", org.apache.thrift.TFieldRequirementType.OPTIONAL, 
        new org.apache.thrift.meta_data.ListMetaData(org.apache.thrift.protocol.TType.LIST, 
            new org.apache.thrift.meta_data.FieldValueMetaData(org.apache.thrift.protocol.TType.STRING))));
    metaDataMap = Collections.unmodifiableMap(tmpMap);
    org.apache.thrift.meta_data.FieldMetaData.addStructMetaDataMap(AppletRef.class, metaDataMap);
  }

  public AppletRef() {
  }

  public AppletRef(
    String pipeline,
    String instance,
    String applet)
  {
    this();
    this.pipeline = pipeline;
    this.instance = instance;
    this.applet = applet;
  }

  /**
   * Performs a deep copy on <i>other</i>.
   */
  public AppletRef(AppletRef other) {
    if (other.isSetPipeline()) {
      this.pipeline = other.pipeline;
    }
    if (other.isSetInstance()) {
      this.instance = other.instance;
    }
    if (other.isSetApplet()) {
      this.applet = other.applet;
    }
    if (other.isSetKeys()) {
      List<String> __this__keys = new ArrayList<String>();
      for (String other_element : other.keys) {
        __this__keys.add(other_element);
      }
      this.keys = __this__keys;
    }
  }

  public AppletRef deepCopy() {
    return new AppletRef(this);
  }

  @Override
  public void clear() {
    this.pipeline = null;
    this.instance = null;
    this.applet = null;
    this.keys = null;
  }

  public String getPipeline() {
    return this.pipeline;
  }

  public AppletRef setPipeline(String pipeline) {
    this.pipeline = pipeline;
    return this;
  }

  public void unsetPipeline() {
    this.pipeline = null;
  }

  /** Returns true if field pipeline is set (has been assigned a value) and false otherwise */
  public boolean isSetPipeline() {
    return this.pipeline != null;
  }

  public void setPipelineIsSet(boolean value) {
    if (!value) {
      this.pipeline = null;
    }
  }

  public String getInstance() {
    return this.instance;
  }

  public AppletRef setInstance(String instance) {
    this.instance = instance;
    return this;
  }

  public void unsetInstance() {
    this.instance = null;
  }

  /** Returns true if field instance is set (has been assigned a value) and false otherwise */
  public boolean isSetInstance() {
    return this.instance != null;
  }

  public void setInstanceIsSet(boolean value) {
    if (!value) {
      this.instance = null;
    }
  }

  public String getApplet() {
    return this.applet;
  }

  public AppletRef setApplet(String applet) {
    this.applet = applet;
    return this;
  }

  public void unsetApplet() {
    this.applet = null;
  }

  /** Returns true if field applet is set (has been assigned a value) and false otherwise */
  public boolean isSetApplet() {
    return this.applet != null;
  }

  public void setAppletIsSet(boolean value) {
    if (!value) {
      this.applet = null;
    }
  }

  public int getKeysSize() {
    return (this.keys == null) ? 0 : this.keys.size();
  }

  public java.util.Iterator<String> getKeysIterator() {
    return (this.keys == null) ? null : this.keys.iterator();
  }

  public void addToKeys(String elem) {
    if (this.keys == null) {
      this.keys = new ArrayList<String>();
    }
    this.keys.add(elem);
  }

  public List<String> getKeys() {
    return this.keys;
  }

  public AppletRef setKeys(List<String> keys) {
    this.keys = keys;
    return this;
  }

  public void unsetKeys() {
    this.keys = null;
  }

  /** Returns true if field keys is set (has been assigned a value) and false otherwise */
  public boolean isSetKeys() {
    return this.keys != null;
  }

  public void setKeysIsSet(boolean value) {
    if (!value) {
      this.keys = null;
    }
  }

  public void setFieldValue(_Fields field, Object value) {
    switch (field) {
    case PIPELINE:
      if (value == null) {
        unsetPipeline();
      } else {
        setPipeline((String)value);
      }
      break;

    case INSTANCE:
      if (value == null) {
        unsetInstance();
      } else {
        setInstance((String)value);
      }
      break;

    case APPLET:
      if (value == null) {
        unsetApplet();
      } else {
        setApplet((String)value);
      }
      break;

    case KEYS:
      if (value == null) {
        unsetKeys();
      } else {
        setKeys((List<String>)value);
      }
      break;

    }
  }

  public Object getFieldValue(_Fields field) {
    switch (field) {
    case PIPELINE:
      return getPipeline();

    case INSTANCE:
      return getInstance();

    case APPLET:
      return getApplet();

    case KEYS:
      return getKeys();

    }
    throw new IllegalStateException();
  }

  /** Returns true if field corresponding to fieldID is set (has been assigned a value) and false otherwise */
  public boolean isSet(_Fields field) {
    if (field == null) {
      throw new IllegalArgumentException();
    }

    switch (field) {
    case PIPELINE:
      return isSetPipeline();
    case INSTANCE:
      return isSetInstance();
    case APPLET:
      return isSetApplet();
    case KEYS:
      return isSetKeys();
    }
    throw new IllegalStateException();
  }

  @Override
  public boolean equals(Object that) {
    if (that == null)
      return false;
    if (that instanceof AppletRef)
      return this.equals((AppletRef)that);
    return false;
  }

  public boolean equals(AppletRef that) {
    if (that == null)
      return false;

    boolean this_present_pipeline = true && this.isSetPipeline();
    boolean that_present_pipeline = true && that.isSetPipeline();
    if (this_present_pipeline || that_present_pipeline) {
      if (!(this_present_pipeline && that_present_pipeline))
        return false;
      if (!this.pipeline.equals(that.pipeline))
        return false;
    }

    boolean this_present_instance = true && this.isSetInstance();
    boolean that_present_instance = true && that.isSetInstance();
    if (this_present_instance || that_present_instance) {
      if (!(this_present_instance && that_present_instance))
        return false;
      if (!this.instance.equals(that.instance))
        return false;
    }

    boolean this_present_applet = true && this.isSetApplet();
    boolean that_present_applet = true && that.isSetApplet();
    if (this_present_applet || that_present_applet) {
      if (!(this_present_applet && that_present_applet))
        return false;
      if (!this.applet.equals(that.applet))
        return false;
    }

    boolean this_present_keys = true && this.isSetKeys();
    boolean that_present_keys = true && that.isSetKeys();
    if (this_present_keys || that_present_keys) {
      if (!(this_present_keys && that_present_keys))
        return false;
      if (!this.keys.equals(that.keys))
        return false;
    }

    return true;
  }

  @Override
  public int hashCode() {
    return 0;
  }

  public int compareTo(AppletRef other) {
    if (!getClass().equals(other.getClass())) {
      return getClass().getName().compareTo(other.getClass().getName());
    }

    int lastComparison = 0;
    AppletRef typedOther = (AppletRef)other;

    lastComparison = Boolean.valueOf(isSetPipeline()).compareTo(typedOther.isSetPipeline());
    if (lastComparison != 0) {
      return lastComparison;
    }
    if (isSetPipeline()) {
      lastComparison = org.apache.thrift.TBaseHelper.compareTo(this.pipeline, typedOther.pipeline);
      if (lastComparison != 0) {
        return lastComparison;
      }
    }
    lastComparison = Boolean.valueOf(isSetInstance()).compareTo(typedOther.isSetInstance());
    if (lastComparison != 0) {
      return lastComparison;
    }
    if (isSetInstance()) {
      lastComparison = org.apache.thrift.TBaseHelper.compareTo(this.instance, typedOther.instance);
      if (lastComparison != 0) {
        return lastComparison;
      }
    }
    lastComparison = Boolean.valueOf(isSetApplet()).compareTo(typedOther.isSetApplet());
    if (lastComparison != 0) {
      return lastComparison;
    }
    if (isSetApplet()) {
      lastComparison = org.apache.thrift.TBaseHelper.compareTo(this.applet, typedOther.applet);
      if (lastComparison != 0) {
        return lastComparison;
      }
    }
    lastComparison = Boolean.valueOf(isSetKeys()).compareTo(typedOther.isSetKeys());
    if (lastComparison != 0) {
      return lastComparison;
    }
    if (isSetKeys()) {
      lastComparison = org.apache.thrift.TBaseHelper.compareTo(this.keys, typedOther.keys);
      if (lastComparison != 0) {
        return lastComparison;
      }
    }
    return 0;
  }

  public _Fields fieldForId(int fieldId) {
    return _Fields.findByThriftId(fieldId);
  }

  public void read(org.apache.thrift.protocol.TProtocol iprot) throws org.apache.thrift.TException {
    org.apache.thrift.protocol.TField field;
    iprot.readStructBegin();
    while (true)
    {
      field = iprot.readFieldBegin();
      if (field.type == org.apache.thrift.protocol.TType.STOP) { 
        break;
      }
      switch (field.id) {
        case 1: // PIPELINE
          if (field.type == org.apache.thrift.protocol.TType.STRING) {
            this.pipeline = iprot.readString();
          } else { 
            org.apache.thrift.protocol.TProtocolUtil.skip(iprot, field.type);
          }
          break;
        case 2: // INSTANCE
          if (field.type == org.apache.thrift.protocol.TType.STRING) {
            this.instance = iprot.readString();
          } else { 
            org.apache.thrift.protocol.TProtocolUtil.skip(iprot, field.type);
          }
          break;
        case 3: // APPLET
          if (field.type == org.apache.thrift.protocol.TType.STRING) {
            this.applet = iprot.readString();
          } else { 
            org.apache.thrift.protocol.TProtocolUtil.skip(iprot, field.type);
          }
          break;
        case 4: // KEYS
          if (field.type == org.apache.thrift.protocol.TType.LIST) {
            {
              org.apache.thrift.protocol.TList _list0 = iprot.readListBegin();
              this.keys = new ArrayList<String>(_list0.size);
              for (int _i1 = 0; _i1 < _list0.size; ++_i1)
              {
                String _elem2;
                _elem2 = iprot.readString();
                this.keys.add(_elem2);
              }
              iprot.readListEnd();
            }
          } else { 
            org.apache.thrift.protocol.TProtocolUtil.skip(iprot, field.type);
          }
          break;
        default:
          org.apache.thrift.protocol.TProtocolUtil.skip(iprot, field.type);
      }
      iprot.readFieldEnd();
    }
    iprot.readStructEnd();

    // check for required fields of primitive type, which can't be checked in the validate method
    validate();
  }

  public void write(org.apache.thrift.protocol.TProtocol oprot) throws org.apache.thrift.TException {
    validate();

    oprot.writeStructBegin(STRUCT_DESC);
    if (this.pipeline != null) {
      oprot.writeFieldBegin(PIPELINE_FIELD_DESC);
      oprot.writeString(this.pipeline);
      oprot.writeFieldEnd();
    }
    if (this.instance != null) {
      oprot.writeFieldBegin(INSTANCE_FIELD_DESC);
      oprot.writeString(this.instance);
      oprot.writeFieldEnd();
    }
    if (this.applet != null) {
      oprot.writeFieldBegin(APPLET_FIELD_DESC);
      oprot.writeString(this.applet);
      oprot.writeFieldEnd();
    }
    if (this.keys != null) {
      if (isSetKeys()) {
        oprot.writeFieldBegin(KEYS_FIELD_DESC);
        {
          oprot.writeListBegin(new org.apache.thrift.protocol.TList(org.apache.thrift.protocol.TType.STRING, this.keys.size()));
          for (String _iter3 : this.keys)
          {
            oprot.writeString(_iter3);
          }
          oprot.writeListEnd();
        }
        oprot.writeFieldEnd();
      }
    }
    oprot.writeFieldStop();
    oprot.writeStructEnd();
  }

  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder("AppletRef(");
    boolean first = true;

    sb.append("pipeline:");
    if (this.pipeline == null) {
      sb.append("null");
    } else {
      sb.append(this.pipeline);
    }
    first = false;
    if (!first) sb.append(", ");
    sb.append("instance:");
    if (this.instance == null) {
      sb.append("null");
    } else {
      sb.append(this.instance);
    }
    first = false;
    if (!first) sb.append(", ");
    sb.append("applet:");
    if (this.applet == null) {
      sb.append("null");
    } else {
      sb.append(this.applet);
    }
    first = false;
    if (isSetKeys()) {
      if (!first) sb.append(", ");
      sb.append("keys:");
      if (this.keys == null) {
        sb.append("null");
      } else {
        sb.append(this.keys);
      }
      first = false;
    }
    sb.append(")");
    return sb.toString();
  }

  public void validate() throws org.apache.thrift.TException {
    // check for required fields
    if (pipeline == null) {
      throw new org.apache.thrift.protocol.TProtocolException("Required field 'pipeline' was not present! Struct: " + toString());
    }
    if (instance == null) {
      throw new org.apache.thrift.protocol.TProtocolException("Required field 'instance' was not present! Struct: " + toString());
    }
    if (applet == null) {
      throw new org.apache.thrift.protocol.TProtocolException("Required field 'applet' was not present! Struct: " + toString());
    }
  }

  private void writeObject(java.io.ObjectOutputStream out) throws java.io.IOException {
    try {
      write(new org.apache.thrift.protocol.TCompactProtocol(new org.apache.thrift.transport.TIOStreamTransport(out)));
    } catch (org.apache.thrift.TException te) {
      throw new java.io.IOException(te);
    }
  }

  private void readObject(java.io.ObjectInputStream in) throws java.io.IOException, ClassNotFoundException {
    try {
      read(new org.apache.thrift.protocol.TCompactProtocol(new org.apache.thrift.transport.TIOStreamTransport(in)));
    } catch (org.apache.thrift.TException te) {
      throw new java.io.IOException(te);
    }
  }

}

