/**
 * Autogenerated by Thrift Compiler (0.8.0)
 *
 * DO NOT EDIT UNLESS YOU ARE SURE THAT YOU KNOW WHAT YOU ARE DOING
 *  @generated
 */
package org.remus.thrift;

import org.apache.thrift.scheme.IScheme;
import org.apache.thrift.scheme.SchemeFactory;
import org.apache.thrift.scheme.StandardScheme;

import org.apache.thrift.scheme.TupleScheme;
import org.apache.thrift.protocol.TTupleProtocol;
import java.util.List;
import java.util.ArrayList;
import java.util.Map;
import java.util.HashMap;
import java.util.EnumMap;
import java.util.Set;
import java.util.HashSet;
import java.util.EnumSet;
import java.util.Collections;
import java.util.BitSet;
import java.nio.ByteBuffer;
import java.util.Arrays;
import org.slf4j.Logger;
import org.slf4j.LoggerFactory;

public class Constants {

  public static final String STATIC_INSTANCE = "00000000-0000-0000-0000-000000000000";

  public static final String PIPELINE_APPLET = "@pipeline";

  public static final String INSTANCE_APPLET = "@instance";

  public static final String SUBMIT_APPLET = "@submit";

  public static final String WORK_APPLET = "@work";

  public static final String ERROR_APPLET = "@error";

  public static final String DONE_APPLET = "@done";

  public static final String ROOT_PIPELINE = "@root";

  public static final String WORKSTAT_APPLET = "@workstat";

}
